In [3]:
import numpy as np
print(np. __version__ )


arr = np.array([1, 2, 3, 4, 5])

print(arr)



2.4.2
[1 2 3 4 5]


In [4]:


ar= np.array([1,2,3,4,5,6]) # 1d array

print(type(ar))

<class 'numpy.ndarray'>


In [11]:
ar= np.array([23,56,78])
print(ar[1:])
print(ar[2])
print(ar[1:2])

[56 78]
78
[56]


In [ ]:
sb= np.array(["saba", "rabia", "ayesha", 56, "true"]) 
print(sb.dtype) # checking datatype of array


<U21
[1. 1. 1. 1. 1.]


In [19]:
fruits= np.array(["apple", "bananaaaa", "kiwi"])
x=fruits.copy() # original array change ho gi or copy wali array same hi rahy gi
x[1]= "pineapple"
print(fruits)
print(x)

['apple' 'bananaaaa' 'kiwi']
['apple' 'pineapple' 'kiwi']


In [16]:
number= np.array([23,45,67])
y=number.view() #  aik array ma changes krny sy dosari array b effect ho rahi
number[1]=34 
print(number)
print(y)
onr=np.ones(5) 
print(onr)

[23 34 67]
[23 34 67]
[1. 1. 1. 1. 1.]


In [ ]:
rollnumber=np.array([[1,2,3,4],[3,4,5,6]])
print(rollnumber.shape) # tells the shape of array like 1d 2d 3d or multi demension


(2, 4)


In [11]:
num= np.array([[1,2,3,4],[2,3,5,7]], ndmin=6)
print(num)



[[[[[[1 2 3 4]
     [2 3 5 7]]]]]]


In [13]:
num.shape

(1, 1, 1, 1, 2, 4)

In [ ]:
a=np.arange(1,10,2)
print(a)
a.reshape(5,1) #5 rows and 1 column
a.reshape(5,1,1) # 5 block 1 row 1 colum


[1 3 5 7 9]


array([[[1]],

       [[3]],

       [[5]],

       [[7]],

       [[9]]])