In [8]:
import numpy as np
num = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=num.reshape(2,6) # converting 1D to 2D
arr2= num.reshape(2, 2,3)
print("3d array", arr2)
print(arr1)

3d array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


indexing and slicing

In [22]:
num[2]=10
print(num[3:])
print(num[:3])
print(num[-2])
print(num)





[ 4  5  6  7  8  9 10 11 12]
[ 1  2 10]
11
[ 1  2 10  4  5  6  7  8  9 10 11 12]


In [27]:
np.linspace(0,2,9) #np.linspace(start, stop, num)
np.zeros((3,4), dtype=int) #zeros() is used to create an array filled with 0 values. zero(rows,colum, dtype)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

Create a constant array 

In [37]:
e = np.full((2,2),7) #np.full(shape, value)
e

#Create a 2X2 identity matrix
f = np.eye(2)
f

# Create an array with random values
np.random.random((5))

array([0.92291145, 0.74735184, 0.5388919 , 0.55593429, 0.8905002 ])

In [40]:
np.empty((2,4))

array([[0.25, 0.5 , 0.75, 1.  ],
       [1.25, 1.5 , 1.75, 2.  ]])

In [106]:
a=np.array([2,4,5,6,7])
b= np.array([2,4,5,1,4])
print(a.size)
print(a.shape)
print(a.ndim)

np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)
np.exp(b)
np.sqrt(a)
np.cos(a)
np.sin(b)
np.concatenate((a,b))




5
(5,)
1


array([2, 4, 5, 6, 7, 2, 4, 5, 1, 4])

In [113]:
data= np.array([2,3,5,6])
print(data.reshape(4,1,1))

print("min value", data.min())
print("max value", data.max())
print("sum of value", data.sum())

[[[2]]

 [[3]]

 [[5]]

 [[6]]]
min value 2
max value 6
sum of value 16


In [67]:
data= np.array([1,2,1,1,3,3,8])
np.unique_values(data)
data.reshape(7,1,1)

array([[[1]],

       [[2]],

       [[1]],

       [[1]],

       [[3]],

       [[3]],

       [[8]]])

In [75]:
a= np.arange(1,13,2).reshape(2,3)
a
a.transpose()

array([[ 1,  7],
       [ 3,  9],
       [ 5, 11]])

In [87]:
arr= np.array([[2,3,4,5,6],[12,13,14,15,16]])
arry2=np.flip(arr, axis=1) # reverse an array
print(arry2)

[[ 6  5  4  3  2]
 [16 15 14 13 12]]


In [ ]:
num= np.array([10,2,4,5,6])
newarry=num.flatten() # will not change the parent array
newarry[1]=23
print(newarry)
print(num)


[10 23  4  5  6]
[10  2  4  5  6]


In [ ]:
num= np.array([10,2,4,5,6])
newarry=num.ravel() # changing efects parent and child array
newarry[1]=23
print(newarry)
print(num)


[10 23  4  5  6]
[10 23  4  5  6]


In [100]:
num= np.array([2,3,9,6,5,4])
np.sort(num)
np.argsort(num)
np.lexsort(num) # multiple keys k sath sort
np.searchsorted(num,3)


np.int64(1)

In [124]:
a= np.array([1,2,3,4,5])
c= a[np.newaxis, :]
print(c)
print(c.shape)
print(c.ndim)

c= a[:, np.newaxis]
print(c.shape) 


  



[[1 2 3 4 5]]
(1, 5)
2
(5, 1)


In [139]:
arr= np.arange(250)
newarry=arr.reshape(5,5,10)
print(newarry)
print("Accessing element in midle", newarry[3,4,5]) # (block, row, column)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]]

 [[ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]]

 [[100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]]

 [[150 151 152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 222 223 224 2